alias php='/usr/bin/php -d memory_limit=1024M -d log_errors=on -d error_log=/var/www/vhosts/localhost/php.log -d error_reporting=32767'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'