name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: AhnSeongHyun/action-tag-docker-build-push@master
        with:
          repo_name: bakasura/spotweb
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
